title: Thanh's Journal
description: Perspectives on Politics, Tech & Life
baseurl: ""
url: "https://thanhbach0904.github.io"
author: Thanh

timezone: Asia/Ho_Chi_Minh
permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

tags_list:
  - { slug: "politics", label: "Politics" }
  - { slug: "analysis", label: "Analysis" }
  - { slug: "technical", label: "Technical" }
  - { slug: "books", label: "Books" }
  - { slug: "life", label: "Life's Perspectives" }
